python3
NETWAYS/check_hp_msa pull request #2
Opened 2021-05-02 03:56 UTC by KornM

2021-05-10 15:25 UTC, lazyfrosch requested changes
Would be great when all API types follow the same health logic - wasn't sure if this is the case.

Still this would block the way to check certain additional props apart from

Code styling in general can be improved :wink:
- whitespacing
- no `camelCasing` in Python, use [snake case as in PEP8](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names)

2021-05-10 15:25 UTC, lazyfrosch commented on check_hp_msa.py
> +        self.debug_outdir = 'tmp/'
Should not be enabled by default - and become an option later

2021-05-10 15:25 UTC, lazyfrosch commented on check_hp_msa.py
> +        mode = client.kget_component( "disks", "drives",output)
What is `kget_component` ?

2021-05-10 15:25 UTC, lazyfrosch commented on check_hp_msa.py
> +                        self.perfdata.append(f"{self.objectName}_pct_{name}={pct}")
Perfdata label should be cleaned up and special chars replaced by `_`, so we have sth like `number_of_disks`

2021-05-10 15:25 UTC, lazyfrosch commented on check_hp_msa.py
> +                        self.perfdata.append(f"{self.objectName}_{perfDataLine}={p[perfDataLine]}")
Perfdata label should be cleaned up and special chars replaced by `_`, so we have sth like `number_of_disks`

2021-05-10 15:27 UTC, lazyfrosch requested changes
Few more notes

2021-05-10 15:27 UTC, lazyfrosch commented on check_hp_msa.py
> +#!/usr/bin/env python3
Don't do this, `venv` takes care of setting the proper `python` target. Should only be changed on installation.

2021-05-10 15:27 UTC, lazyfrosch commented on check_hp_msa.py
> +            requests.packages.urllib3.disable_warnings()
This can fail in certain environments

2021-05-10 15:29 UTC, lazyfrosch commented
Do you want me to work on the PR?

It would be nice to add fixtures, so we can add testing as well, similar to: https://github.com/NETWAYS/check_hp_msa/blob/main/test/fixtures/show-disks.xml

Please anonymize!

2021-05-17 14:55 UTC, KornM commented
Thanks for the annotations, will work on it as soon as I find some spare
time

Am Mo., 10. Mai 2021 um 17:29 Uhr schrieb Markus Frosch <
***@***.***>:

> Do you want me to work on the PR?
>
> It would be nice to add fixtures, so we can add testing as well, similar
> to:
> https://github.com/NETWAYS/check_hp_msa/blob/main/test/fixtures/show-disks.xml
>
> Please anonymize!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NETWAYS/check_hp_msa/pull/2#issuecomment-836841126>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEN7MMTUMUDDMHDYIQZAKPTTM73VVANCNFSM4367HDLA>
> .
>

2023-04-17 12:39 UTC, martialblog commented
Marked as stale. Can be reopened with the requested changes anytime.

2023-04-17 12:39 UTC, closed without merging